version: '3.7'
services:
  django:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "
      ./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/meditrack
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - "6378:6378"

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pytest"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: